# Generated by Django 5.0.2 on 2024-02-14 12:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideMinistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=250, null=True)),
                ('description', models.TextField(blank=True, help_text='Описание', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMinistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название песни', max_length=250, null=True)),
                ('media', models.URLField(blank=True, help_text='Ссылка на видео с YouTube', null=True)),
                ('key', models.CharField(blank=True, choices=[('Ab', 'Ab'), ('A', 'A'), ('A#', 'A#'), ('Bb', 'Bb'), ('H', 'H'), ('C', 'C'), ('C#', 'C#'), ('Db', 'Db'), ('D', 'D'), ('D#', 'D#'), ('Eb', 'Eb'), ('E', 'E'), ('F', 'F'), ('F#', 'F#'), ('Gb', 'Gb'), ('G', 'G'), ('G#', 'G#')], default='C', help_text='Тональность', max_length=2, null=True)),
                ('bpm', models.PositiveIntegerField(blank=True, help_text='Метроном', null=True, validators=[django.core.validators.MaxValueValidator(400)])),
                ('tse', models.CharField(blank=True, help_text='Размер Такта', max_length=5, null=True)),
                ('text', models.TextField(help_text='Текст песни', max_length=10000, null=True)),
                ('structure', models.TextField(blank=True, help_text='Структура', max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_edit', 'Can edit Song')],
            },
        ),
        migrations.CreateModel(
            name='SongMinistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название', max_length=250, null=True)),
                ('songs', models.ManyToManyField(blank=True, help_text='Песни', to='index.song')),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата планирования', null=True)),
                ('time', models.TimeField(help_text='Время планирования', null=True)),
                ('name', models.CharField(help_text='Название', max_length=250, null=True)),
                ('description', models.TextField(blank=True, help_text='Описание', null=True)),
                ('bible_passage', models.TextField(blank=True, help_text='Места из Библии', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('invited_user', models.ManyToManyField(blank=True, help_text='Пригласить пользователя', to=settings.AUTH_USER_MODEL)),
                ('slides', models.ManyToManyField(blank=True, help_text='Слайды', to='index.slideministry')),
                ('songs', models.ManyToManyField(blank=True, help_text='Программа', related_name='new_songs', to='index.songministry')),
                ('type', models.ForeignKey(blank=True, help_text='Вид служения', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='index.typeministry')),
            ],
            options={
                'permissions': [('can_edit', 'Can edit Ministry')],
            },
        ),
    ]
