# Generated by Django 5.0.2 on 2024-02-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministry',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='songministry',
            name='songs',
        ),
        migrations.AddField(
            model_name='songministry',
            name='songs',
            field=models.ForeignKey(blank=True, help_text='Программа', null=True, on_delete=django.db.models.deletion.CASCADE, to='index.ministry'),
        ),
    ]
