# Generated by Django 5.0.2 on 2024-02-16 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_songministry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='date',
            field=models.DateField(blank=True, help_text='Дата', null=True),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='name',
            field=models.CharField(blank=True, help_text='Название', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='time',
            field=models.TimeField(blank=True, help_text='Время', null=True),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Вид служения', null=True, on_delete=django.db.models.deletion.CASCADE, to='index.typeministry'),
        ),
    ]
